### ISSUE TITLE
Migration to version 13.0

### ISSUE THREAD

**Issue by jjscarafia** [ingadhoc/product#283]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0

# Modules to migrate

- [ ] product_uoms_sale
- [ ] product_pricelist
- [ ] product_uoms_purchase
- [ ] product_uoms
- [ ] product_price_taxes_included
- [ ] product_attribute_template
- [ ] product_stock_by_location
- [ ] product_internal_code
- [ ] product_catalog_aeroo_report
- [ ] product_replenishment_cost
- [ ] price_security
- [ ] product_ux
- [ ] product_unique - By @usmanfarzandali
- [ ] product_template_tree_first
- [ ] price_security_planned_price
- [ ] product_prices_update
- [ ] product_catalog_aeroo_report_public_categ
- [ ] product_currency
- [ ] product_image_url
- [ ] product_management_group
- [ ] product_replenishment_cost_mrp
- [ ] product_sales_abc
- [ ] product_planned_price
- [ ] product_reference_required

**Comment by usmanfarzandali** [comment]
if not ported may i start port product_unique to v13

**Comment by jjscarafia** [comment]
@usmanfarzandali yes please, we'll appreciate it!
