### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by adhoc-transbot** [ingadhoc/product#99]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0

# Modules to migrate

- [x] price_security https://github.com/ingadhoc/product/pull/100
- [ ] price_security_planned_price
- [ ] product_catalog_aeroo_report
- [ ] product_catalog_aeroo_report_public_categ
- [x] product_category_full_name_search
- [x] product_computed_list_price
- [x] product_computed_price_rule
- [ ] product_currency
- [ ] product_internal_code
- [ ] product_no_translation
- [ ] product_other_sale_description
- [ ] product_pack
- [ ] product_price_currency
- [ ] product_price_taxes_included
- [ ] product_pricelist
- [ ] product_prices_update
- [ ] product_purchase_uom
- [ ] product_reference_required
- [ ] product_replenishment_cost
- [ ] product_replenishment_cost_currency
- [ ] product_replenishment_cost_rule
- [ ] product_sale_price_by_margin
- [ ] product_sale_uom
- [ ] product_sales_abc
- [ ] product_salesman_group
- [ ] product_search_supplier_code
- [ ] product_share_father_son
- [ ] product_stock_by_location
- [ ] product_supplier_search
- [ ] product_template_search_by_barcode
- [ ] product_template_tree_first
- [ ] product_template_tree_prices
- [ ] product_unique
- [ ] product_uom_prices
- [ ] product_uom_prices_currency
- [ ] product_variant_imp
- [ ] product_variant_o2o
- [ ] product_website_categ_search
